export const IPC_CHANNELS = {
  trackerGetStatus: 'tracker.getStatus',
  trackerPause: 'tracker.pause',
  trackerResume: 'tracker.resume',
  trackerToggle: 'tracker.toggle',
  trackerStatusChanged: 'tracker.statusChanged',
  statsGetSummary: 'stats.getSummary',
  statsGetTopApps: 'stats.getTopApps',
  statsGetAIToolDailyStats: 'stats.getAIToolDailyStats',
  settingsGet: 'settings.get',
  settingsUpdate: 'settings.update',
  processesGetAITools: 'processes.getAITools',
  processesChanged: 'processes.changed',
  iconsGetAppIcon: 'icons.getAppIcon',
  windowMinimize: 'window.minimize',
  windowMaximize: 'window.maximize',
  windowClose: 'window.close',
  windowRestoredFromTray: 'window.restoredFromTray',
  updaterDownloadProgress: 'updater.downloadProgress',
  updaterCheckNow: 'updater.checkNow',
  // Focus
  focusGetState: 'focus.getState',
  focusStart: 'focus.start',
  focusStop: 'focus.stop',
  focusGetTodayCount: 'focus.getTodayCount',
  focusStateChanged: 'focus.stateChanged',
  // App Limits
  appLimitsGetAll: 'appLimits.getAll',
  appLimitsUpsert: 'appLimits.upsert',
  appLimitsRemove: 'appLimits.remove',
  appLimitsGetStatuses: 'appLimits.getStatuses',
  appLimitsExceeded: 'appLimits.exceeded',
  // Focus Schedules
  focusSchedulesGetAll: 'focusSchedules.getAll',
  focusSchedulesCreate: 'focusSchedules.create',
  focusSchedulesUpdate: 'focusSchedules.update',
  focusSchedulesRemove: 'focusSchedules.remove',
  // Break Reminder
  breakReminderNotify: 'breakReminder.notify'
} as const;
